.TH CAFFEINE "1" "December 2013" "version 2.4"
.SH NAME
caffeine \- A status bar application able to temporarily prevent the activation of both the screensaver and the "sleep" powersaving mode.
.SH SYNOPSIS
.B caffeine
[\-\-help] [\-\-activate[ \-\-time \fIHOURS:MINUTES\fP]|\-\-deactivate]
.SH DESCRIPTION
Caffeine allows the user to temporarily disable screensaving
and power management. Click on the status bar icon to activate it.
.SH OPTIONS
.TP
.BR \-h ", " \-\^\-help
Show help options
.TP
.BR \-a ", " \-\^\-activate
Activate caffeine to disable system power management and screen saving.
.TP
.BR \-d ", " \-\^\-deactivate
Deactivate caffeine to re-enable system power management and screen saving.
.TP
.BR \-t ", " \-\^\-time
Activate Caffeine for HOURS:MINUTES.
.TP
.BR \-p ", " \-\^\-preferences
Start Caffeine with the preferences dialog open; this allows Caffeine to be configured when the tray icon is disabled.
.SH AUTHORS
Isaiah Heyer <freshapplepy@gmail.com> and
Reuben Thomas <rrt@sc3d.org>
